# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c55e767145572e89294dc07291f628a6b626639f709efa6a8f7ddfb9cb51d023a57858b8539ebb313ff3141bde0e96b23b632c09df63d44c8a8c4035f3790d64

test:
  secret_key_base: 915db2e03368a607cc236e1e1c80fc90d7c138c5c07e9b0177060a5f3a7e5cc2a1b73bbc4ef03d4555e763ba4e9053b6a0f89280d99ffbe887c463998fbd922d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
